### ISSUE TITLE
Remove arrows from number inputs

### ISSUE THREAD

**Issue by hardyjosh** [dragonflysun/cyclo-site#30]
I actually don't think this is that useful and it's visually quite distracting.

According to w3schools we can just do:

```css
/* Chrome, Safari, Edge, Opera */
input::-webkit-outer-spin-button,
input::-webkit-inner-spin-button {
  -webkit-appearance: none;
  margin: 0;
}

/* Firefox */
input[type=number] {
  -moz-appearance: textfield;
}
```
